title: Jim Bob Documentation
url: https://nickilby.github.io
baseurl: /status # the sub path of your site, e.g. /blog/

remote_theme: just-the-docs/just-the-docs
search_enabled: true
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
